### ISSUE TITLE
Self Host without docker

### ISSUE THREAD

**Issue by KatiaSishost** [solidtime-io/solidtime#107] opened 2024-06-14 11:06 UTC
In Process.php line 269:

  The command "psql --file="${:LARAVEL_LOAD_PATH}" --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --us
  ername="${:LARAVEL_LOAD_USER}" --dbname="${:LARAVEL_LOAD_DATABASE}"" failed.

  Exit Code: 127(Command not found)

  Working directory: /var/www/html

  Output:
  ================

  Error Output:
  ================
  sh: 1: psql: not found

**Comment by Onatcer** [comment] 2024-06-14 23:08
hi, could you please provide the details on what system/hoster you tried to run it on? and also what commands you executed. 

we provide docker images to deal with platforms specifics and have everything installed that is needed to run solidtime. in this case it looks like you have to install psql but you'll probably need to install quite a lot more than that to get it running.

**Comment by korridor** [comment] 2024-06-30 17:56
We had a report now with the same error message in the Discord channel, and we were able to reproduce the issue.

The problem was that I added a [schema dump](https://laravel.com/docs/11.x/migrations#squashing-migrations) that is only used during the first migration run. That is not really a issue, but running the schema dump requires the pgsql client command line tool (in addition to the pgsql PHP extension), which is often not installed in setups. Since I was not aware that this is required, I also did not add this to our Dockerfile, so the issue was also relevant for people using the docker image after I added the database dump.

I just pushed a fix that makes the schema dump only relevant for unit tests. Please try if the issue persists with the most current commit in the `main` branch. We'll add a new tag in the following days.

If you need to run a migration in an older release and you have that problem, please try to run the following command before running the first migration: `docker compose exec scheduler rm database/schema/pgsql-schema.sql` or for non-docker users: `rm database/schema/pgsql-schema.sql` (in the project directory)

**Comment by korridor** [comment] 2024-07-03 15:18
The release [v0.0.3](https://github.com/solidtime-io/solidtime/releases/tag/v0.0.3) fixes this issue.

**Closed by korridor** 2024-07-03 15:18 UTC

**Comment by John-H-Smith** [comment] 2024-10-13 17:25
Hi there,
Just discovered your project, seems quite great!
But now I have the very same issue running the docker-compose.yml from your example repository (which states the usage of the -latest tag). So is this maybe still an issue?

**Comment by korridor** [comment] 2024-10-15 10:36
@John-H-Smith Thanks for the info, we'll look into it. Someone created a new issue for this here, so will post updates about this issue there: https://github.com/solidtime-io/self-hosting-examples/issues/4

**Comment by korridor** [comment] 2024-10-15 10:55
@John-H-Smith The problem should be resolved now. Please pull `latest` again and restart.
